# choose a activate Message
ActivateMessage: "§l§eSV §r§7> §aYou activated Supervanish!"
# a Message when you activated vanish for other
ActivateOtherMessage: "§l§eSV §r§7> §aYou activated Supervanish for this player!"
# And a Message when your vanish was activated by other
ActivateByOtherMessage: "§l§eSV §r§7> §aYour Supervanish has been activated!"
# And now a message for deactivating 
DeactivateMessage: "§l§eSV §r§7> §cYou deactivated Supervanish!"
# Now a message when you deactivated vanish for other
DeactivateOtherMessage: "§l§eSV §r§7-> §cYou deactivated Supervanish for this player!"
# And for the case when your vanish was deactivated by other
DeactivateByOtherMessage: "§l§eSV §r§7> §cYour vanish has been deactivated!"
# So, last thing: if a player want's to change vanish mode for an offline / invalid player 
InvalidPlayer: "§l§eSV §r§7> §4Error! Player not found!"
