# Use  §  - for color codes and  \n  - for next line
activate:
  self: "§l§eSV §r§7> §aYou activated vanish mode"
  other: "§l§eSV §r§7> §aYou activated vanish mode of Player §e{player}"
  byother: "§l§eSV §r§7> §aYour vanish mode has been activated by Player §e{player}"

deactivate:
  self: "§l§eSV §r§7> §cYou deactivated vanish mode"
  other: "§l§eSV §r§7> §cYou deactivated vanish mode of Player §e{player}"
  byother: "§l§eSV §r§7> §cYour vanish mode has been deactivated by Player §e{player}"

NoPermission: "§l§eSV §r§7> §cYou do not have the permission to execute this command!"
InvalidPlayer: "§l§eSV §r§7> §4Player not found!"
